data_loader:
  data_dir: /mnt/onboard_data/training_data/v1
  input_fnames_list : /mnt/onboard_data/training_data/fnames1.csv

train:
   run_id: 20230802_debug1 # if missing auto generates unique

   run_dir: /mnt/training/
   log_dir: /mnt/training/<run_id>/logs/
   ckpt_dir: /mnt/training/<run_id>/checkpoints/
   out_dir: /mnt/training/<run_id>/

   wandb_mode: offline # online or offline or disabled

   resume_from_checkpoint: True
   ckpt_path: last # path or "last"

   model: bmshj2018_factorized
   quality: 2
   learning_rate: 1.e-3
   learning_rate_schedule_patience: 10
   batch_size: 4
   img_size: 512
   loss: mssim  # mssim or mse or rmse_sw or psnr
   nepochs: 100
   log_every_n_steps: 10
