Training:
  working_directory: '/workspace/batches'  # directory for intermediate data conversion
  batch_size: 8192                                        # number of rays per gradient step (power of 2)
  num_workers: 64                                         # number of workers for data loading
  log_every_n_steps: null                                 # log images and save states between epochs

Lambda:
  regularization: 1

Debug: False