Training:
  working_directory: '/mnt/ground-data/batches'           # directory for intermediate data conversion
  n_epochs: 1000                                          # number of updates for all available rays
  batch_size: 1024                                        # number of rays per gradient step (power of 2)
  points_batch_size: 1024                                 # number of points per gradient step (power of 2)
  num_workers: 32                                         # number of workers for data loading
  log_every_n_steps: 500                                 # log images and save states between epochs

Lambda:
  continuity: 1.e-3
  radial_regularization: 1.e-2
  velocity_regularization: 1.e-2
  tB: 0.
  pB: 10.

Debug: False